import numpy

class Rollout:
    def __init__(self, nthread: int) -> None: ...
    def rollout(self, model: list, data: list, nstep: int, control_spec: int, state0: numpy.ndarray[numpy.float64], warmstart0: numpy.ndarray[numpy.float64] | None = ..., control: numpy.ndarray[numpy.float64] | None = ..., state: numpy.ndarray[numpy.float64] | None = ..., sensordata: numpy.ndarray[numpy.float64] | None = ..., chunk_size: int | None = ...) -> None: ...
