import mujoco._render
import numpy
from typing import ClassVar

class Mutex:
    def __init__(self, *args, **kwargs) -> None: ...
    def __enter__(self) -> None: ...
    def __exit__(self, arg0: object, arg1: object, arg2: object) -> None: ...

class Simulate:
    MAX_GEOM: ClassVar[int] = ...  # read-only
    droploadrequest: int
    load_error: str
    measured_slowdown: float
    speed_changed: bool
    ui0_enable: int
    ui1_enable: int
    def __init__(self, arg0: object, arg1: object, arg2: object, arg3: object, arg4: bool, arg5: object) -> None: ...
    def add_to_history(self) -> None: ...
    def clear_figures(self) -> None: ...
    def clear_images(self) -> None: ...
    def clear_texts(self) -> None: ...
    def destroy(self) -> None: ...
    def exit(self) -> None: ...
    def load(self, arg0: object, arg1: object, arg2: str) -> None: ...
    def load_message(self, arg0: str) -> None: ...
    def load_message_clear(self) -> None: ...
    def lock(self) -> Mutex: ...
    def render_loop(self) -> None: ...
    def set_figures(self, viewports_figures: list[tuple[mujoco._render.MjrRect, object]]) -> None: ...
    def set_images(self, viewports_images: list[tuple[mujoco._render.MjrRect, numpy.ndarray]]) -> None: ...
    def set_texts(self, overlay_texts: list[tuple[int, int, str, str]]) -> None: ...
    def sync(self, state_only: bool = ...) -> None: ...
    def uiloadrequest_decrement(self) -> None: ...
    def update_hfield(self, arg0: int) -> None: ...
    def update_mesh(self, arg0: int) -> None: ...
    def update_texture(self, arg0: int) -> None: ...
    @property
    def busywait(self) -> int: ...
    @property
    def ctrl_noise_rate(self) -> float: ...
    @property
    def ctrl_noise_std(self) -> float: ...
    @property
    def d(self) -> object: ...
    @property
    def dropfilename(self) -> str: ...
    @property
    def exitrequest(self) -> int: ...
    @property
    def filename(self) -> str: ...
    @property
    def m(self) -> object: ...
    @property
    def real_time_index(self) -> int: ...
    @property
    def refresh_rate(self) -> int: ...
    @property
    def run(self) -> int: ...
    @property
    def uiloadrequest(self) -> int: ...
    @property
    def viewport(self) -> mujoco._render.MjrRect: ...

def set_glfw_dlhandle(arg0: int) -> None: ...
